# Generated by Django 5.2 on 2025-05-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeustotil', '0002_responsable_rename_responsble_tarea_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='responsable',
        ),
        migrations.AddField(
            model_name='tarea',
            name='responsable',
            field=models.ManyToManyField(to='appdeustotil.empleado'),
        ),
    ]
