# Generated by Django 5.2 on 2025-05-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeustotil', '0004_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
