# Generated by Django 5.2 on 2025-05-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeustotil', '0005_proyecto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
