# Generated by Django 5.2 on 2025-05-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeustotil', '0005_proyecto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='codigo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
