# Generated by Django 5.2 on 2025-05-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdeustotil', '0006_tarea_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='codigo',
        ),
    ]
