# Generated by Django 5.2 on 2025-05-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeustotil', '0008_alter_proyecto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='codigo',
        ),
        migrations.AddField(
            model_name='tarea',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
