# Generated by Django 5.2 on 2025-05-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeustotil', '0010_remove_tarea_codigo_proyecto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(default='001A', max_length=50),
        ),
    ]
