# Generated by Django 5.2 on 2025-05-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeustotil', '0011_alter_proyecto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
