# Generated by Django 5.2 on 2025-05-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdeustotil', '0007_remove_tarea_codigo'),
        ('appdeustotil', '0013_alter_proyecto_codigo'),
    ]

    operations = [
    ]
