# Generated by Django 5.2 on 2025-05-20 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdeustotil', '0015_remove_proyecto_tareas_proyecto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdeustotil.proyecto'),
        ),
    ]
